### ISSUE TITLE
should have polyfill

### ISSUE THREAD

**Issue by jaydeep987** [bukacekd/Dialog#1]
This is amazing lib. and it is using modern `dialog` element.
But it should have polyfill for old/unsupported browsers.. I don't have much time otherwise could create a PR.
looking forward for this update!

**Comment by bukacekd** [comment]
To make the library work in older browsers (depending on the version), it would be necessary to add polyfills for **dialog** (https://github.com/GoogleChrome/dialog-polyfill) and **getAnimations** (https://github.com/web-animations/web-animations-js -> https://unpkg.com/browse/web-animations-js@2.3.2/web-animations-next.min.js)

Problems may still occur, e.g.
- opening and closing the dialog would not wait for css transitions or animations to complete
- broken accessibility,
- inability to style the ::backdrop pseudo element, see https://github.com/GoogleChrome/dialog-polyfill#limitations

Any user can add the above described or similar polyfills to their project. Even so, the library may not behave correctly. Sorry, but for these reasons polyfills will never be part of the library itself.
